repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: make-fmt
        name: Run formatter (make fmt)
        entry: make fmt
        language: system
        pass_filenames: false
        always_run: true
      - id: make-lint
        name: Run linter (make lint)
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
      - id: make-check-types
        name: Run type checker (make check_types)
        entry: make check_types
        language: system
        pass_filenames: false
        always_run: true
